### ISSUE TITLE
Syncing wekan groups with OpenLDAP?

### ISSUE THREAD

**Issue by olivierlambert** [KanRule/ldap#93]
Hi there,

I'm not sure if this feature exists or not. If it does, how to configure it? (I currently have a successful user LDAP sync: however, when we create a new board for a "functional team", that would be lovely to avoid adding users one by one, but instead assign a group that will be the same than the LDAP one)

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/3926
